name: Daily unregexle
on:
  workflow_dispatch:
  schedule:
    - cron: "55 15 * * *" # 4PM GMT - 5min
jobs:
  regexle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Chrome setup matters
        run: |-
          apt list --installed
          sudo apt purge google-chrome-stable
          sudo apt purge chromium-browser
          sudo apt install -y chromium-browser
          chromium-browser --version > version.txt
          pip install -r requirements.txt
      - name: It's Regexle time!
        run: for side in {1..32}; do python main.py $side; done
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHATS: ${{ secrets.CHATS }}